# Workflow for code deployment
name: Netlify Continuous Deployment

# Controls when the action will run.
on:
    push:
        branches: [master]

jobs:
    deploy:

        runs-on: ubuntu-latest # Specifies the virtual environment to run the job in.

        defaults:
          run:
            working-directory: './codingtest-app'

        strategy:
            matrix:
              node-version: [18.x]
              # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
               node-version: ${{ matrix.node-version }}
               cache: 'npm'
               cache-dependency-path: './codingtest-app/package-lock.json'

            # Install dependencies, build, and test
            - name: Install dependencies
              run: npm ci
            - name: Build site
              run: npm build
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test

            # Deploy to Netlify 
            - name: Deploy site
              run: curl -X POST -d {} ${{ secrets.NETLIFY_DEPLOYMENT_BUILD_HOOK }}