# Workflow for checking code integration
name: Code Integration Check

# Controls when the action will run. Triggers the workflow on push or pull request
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
    build:
        runs-on: ubuntu-latest # The type of runner that the job will run on
        
        
        strategy:
            matrix:
                node-version: [18.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
            
        steps:
            
                - uses: actions/checkout@v4 # Checkout the repository to the GitHub Actions runner
                - name: Use Node.js ${{ matrix.node-version }}
                  uses: actions/setup-node@v4 # Set up Node.js
                  with:
                    node-version: ${{ matrix.node-version }}
                    cache: 'npm'
                    cache-dependency-path: 'package-lock.json'
                
                # Install dependencies, build, and test
                - run: npm ci
                - run: npm run build
                - run: npx playwright install --with-deps
                - run: npx playwright test
                